Repository Techeer-FM-Studio/backend, pull requests merged in 2023-04, with the labels that each got.

#29 Feat : Task 생성 기능 구현
  build.gradle
  src/main/java/com/techeer/fmstudio/domain/task/controller/TaskController.java
  src/main/java/com/techeer/fmstudio/domain/task/controller/TestMemberController.java
  src/main/java/com/techeer/fmstudio/domain/task/dao/SharedMemberRepository.java
  src/main/java/com/techeer/fmstudio/domain/task/dao/TaskRepository.java
  src/main/java/com/techeer/fmstudio/domain/task/dao/TestMemberRepository.java
  src/main/java/com/techeer/fmstudio/domain/task/domain/SharedMember.java
  src/main/java/com/techeer/fmstudio/domain/task/domain/Task.java
  src/main/java/com/techeer/fmstudio/domain/task/domain/TestMember.java
  src/main/java/com/techeer/fmstudio/domain/task/dto/mapper/TaskMapper.java
  src/main/java/com/techeer/fmstudio/domain/task/dto/mapper/TestMemberMapper.java
  src/main/java/com/techeer/fmstudio/domain/task/dto/request/TaskCreateRequest.java
  src/main/java/com/techeer/fmstudio/domain/task/dto/request/TestMemberCreateRequest.java
  src/main/java/com/techeer/fmstudio/domain/task/dto/response/TaskInfo.java
  src/main/java/com/techeer/fmstudio/domain/task/dto/response/TestMemberInfo.java
  src/main/java/com/techeer/fmstudio/domain/task/service/SharedMemberService.java
  src/main/java/com/techeer/fmstudio/domain/task/service/TaskService.java
  src/main/java/com/techeer/fmstudio/domain/task/service/TestMemberService.java
  src/main/java/com/techeer/fmstudio/global/BaseEntity.java
  src/main/java/com/techeer/fmstudio/global/config/JpaAuditingConfig.java
Labels: 기능 구현

#34 멤버 생성 기능 구현
  src/main/java/com/techeer/fmstudio/domain/member/controller/MemberController.java
  src/main/java/com/techeer/fmstudio/domain/member/dao/MemberRepository.java
  src/main/java/com/techeer/fmstudio/domain/member/domain/EnumModel.java
  src/main/java/com/techeer/fmstudio/domain/member/domain/MemberEntity.java
  src/main/java/com/techeer/fmstudio/domain/member/domain/MemberInterest.java
  src/main/java/com/techeer/fmstudio/domain/member/domain/MemberStatus.java
  src/main/java/com/techeer/fmstudio/domain/member/dto/MemberCreateRequest.java
  src/main/java/com/techeer/fmstudio/domain/member/dto/MemberInfo.java
  src/main/java/com/techeer/fmstudio/domain/member/dto/MemberMapper.java
  src/main/java/com/techeer/fmstudio/domain/member/service/MemberService.java
Labels: 기능 구현

#36 커스텀 배너 생성 기능
  src/main/java/com/techeer/fmstudio/domain/banner/controller/BannerController.java
  src/main/java/com/techeer/fmstudio/domain/banner/dao/BannerRepository.java
  src/main/java/com/techeer/fmstudio/domain/banner/domain/Banner.java
  src/main/java/com/techeer/fmstudio/domain/banner/domain/Comment.java
  src/main/java/com/techeer/fmstudio/domain/banner/dto/BannerCreateRequest.java
  src/main/java/com/techeer/fmstudio/domain/banner/dto/BannerInfo.java
  src/main/java/com/techeer/fmstudio/domain/banner/dto/BannerMapper.java
  src/main/java/com/techeer/fmstudio/domain/banner/exception/NotFoundBannerException.java
  src/main/java/com/techeer/fmstudio/domain/banner/service/BannerService.java
  src/main/java/com/techeer/fmstudio/domain/member/dto/MemberInfo.java
  src/main/java/com/techeer/fmstudio/domain/member/dto/MemberMapper.java
  src/main/java/com/techeer/fmstudio/domain/member/exception/NotFoundMemberException.java
  src/main/java/com/techeer/fmstudio/global/error/exception/ErrorCode.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: 기능 구현

#37 Feat : 일정 하나 가져오는 기능, 개인 일정 + 공유 일정 가져오는 기능
  src/main/java/com/techeer/fmstudio/domain/task/controller/SharedMemberController.java
  src/main/java/com/techeer/fmstudio/domain/task/controller/TaskController.java
  src/main/java/com/techeer/fmstudio/domain/task/controller/TestMemberController.java
  src/main/java/com/techeer/fmstudio/domain/task/dao/SharedMemberRepository.java
  src/main/java/com/techeer/fmstudio/domain/task/dao/TaskRepository.java
  src/main/java/com/techeer/fmstudio/domain/task/domain/Task.java
  src/main/java/com/techeer/fmstudio/domain/task/domain/TestMember.java
  src/main/java/com/techeer/fmstudio/domain/task/dto/mapper/SharedMemberMapper.java
  src/main/java/com/techeer/fmstudio/domain/task/dto/mapper/TaskMapper.java
  src/main/java/com/techeer/fmstudio/domain/task/dto/mapper/TestMemberMapper.java
  src/main/java/com/techeer/fmstudio/domain/task/dto/request/TaskCreateRequest.java
  src/main/java/com/techeer/fmstudio/domain/task/dto/request/TaskUpdateRequest.java
  src/main/java/com/techeer/fmstudio/domain/task/dto/response/SharedMemberResponse.java
  src/main/java/com/techeer/fmstudio/domain/task/dto/response/TaskResponse.java
  src/main/java/com/techeer/fmstudio/domain/task/dto/response/TestMemberResponse.java
  src/main/java/com/techeer/fmstudio/domain/task/service/SharedMemberService.java
  src/main/java/com/techeer/fmstudio/domain/task/service/TaskService.java
  src/main/java/com/techeer/fmstudio/domain/task/service/TestMemberService.java
Labels: 기능 구현

#42 Refactor : 일정 엔티티에서 연관관계를 맺은 testmember를 member 엔티티로 변경
  src/main/java/com/techeer/fmstudio/domain/member/dao/MemberRepository.java
  src/main/java/com/techeer/fmstudio/domain/task/controller/TestMemberController.java
  src/main/java/com/techeer/fmstudio/domain/task/dao/SharedMemberRepository.java
  src/main/java/com/techeer/fmstudio/domain/task/dao/TestMemberRepository.java
  src/main/java/com/techeer/fmstudio/domain/task/domain/SharedMember.java
  src/main/java/com/techeer/fmstudio/domain/task/domain/TestMember.java
  src/main/java/com/techeer/fmstudio/domain/task/dto/mapper/SharedMemberMapper.java
  src/main/java/com/techeer/fmstudio/domain/task/dto/mapper/TaskMapper.java
  src/main/java/com/techeer/fmstudio/domain/task/dto/mapper/TestMemberMapper.java
  src/main/java/com/techeer/fmstudio/domain/task/dto/request/TaskUpdateRequest.java
  src/main/java/com/techeer/fmstudio/domain/task/dto/request/TestMemberCreateRequest.java
  src/main/java/com/techeer/fmstudio/domain/task/dto/response/TestMemberResponse.java
  src/main/java/com/techeer/fmstudio/domain/task/exception/NotFoundSharedMemberException.java
  src/main/java/com/techeer/fmstudio/domain/task/exception/NotFoundTaskException.java
  src/main/java/com/techeer/fmstudio/domain/task/service/SharedMemberService.java
  src/main/java/com/techeer/fmstudio/domain/task/service/TaskService.java
  src/main/java/com/techeer/fmstudio/domain/task/service/TestMemberService.java
  src/main/java/com/techeer/fmstudio/global/BaseEntity.java
  src/main/java/com/techeer/fmstudio/global/error/exception/ErrorCode.java
  src/main/resources/application.yml
Labels: enhancement

#49 배너 생성 API 스펙 변화
  src/main/java/com/techeer/fmstudio/domain/banner/controller/BannerController.java
  src/main/java/com/techeer/fmstudio/domain/banner/controller/CustomBannerController.java
  src/main/java/com/techeer/fmstudio/domain/banner/dao/BannerRepository.java
  src/main/java/com/techeer/fmstudio/domain/banner/domain/BannerEntity.java
  src/main/java/com/techeer/fmstudio/domain/banner/domain/BannerType.java
  src/main/java/com/techeer/fmstudio/domain/banner/domain/Comment.java
  src/main/java/com/techeer/fmstudio/domain/banner/domain/LikeMemberList.java
  src/main/java/com/techeer/fmstudio/domain/banner/domain/MyBannerList.java
  src/main/java/com/techeer/fmstudio/domain/banner/dto/BannerInfo.java
  src/main/java/com/techeer/fmstudio/domain/banner/dto/BannerMapper.java
  src/main/java/com/techeer/fmstudio/domain/banner/dto/CustomBannerCreateRequest.java
  src/main/java/com/techeer/fmstudio/domain/banner/service/BannerService.java
  src/main/java/com/techeer/fmstudio/domain/banner/service/CustomBannerService.java
  src/main/java/com/techeer/fmstudio/domain/member/controller/MemberController.java
  src/main/java/com/techeer/fmstudio/domain/member/domain/MemberEntity.java
  src/main/java/com/techeer/fmstudio/domain/member/dto/MemberInfo.java
  src/main/java/com/techeer/fmstudio/domain/member/dto/MemberMapper.java
Labels: 리팩토링

#52 배너에 댓글 생성 기능 구현
  src/main/java/com/techeer/fmstudio/domain/banner/controller/CustomBannerController.java
  src/main/java/com/techeer/fmstudio/domain/banner/dao/CommentRepository.java
  src/main/java/com/techeer/fmstudio/domain/banner/domain/BannerEntity.java
  src/main/java/com/techeer/fmstudio/domain/banner/domain/CommentEntity.java
  src/main/java/com/techeer/fmstudio/domain/banner/dto/mapper/CommentMapper.java
  src/main/java/com/techeer/fmstudio/domain/banner/dto/request/CommentCreateRequest.java
  src/main/java/com/techeer/fmstudio/domain/banner/dto/response/BannerInfo.java
  src/main/java/com/techeer/fmstudio/domain/banner/dto/response/CommentInfo.java
  src/main/java/com/techeer/fmstudio/domain/banner/service/CommentService.java
  src/main/java/com/techeer/fmstudio/domain/banner/service/CustomBannerService.java
  src/main/resources/application.yml
Labels: 기능 구현

#60 배너 id로 하나의 배너 찾기 기능 구현
  src/main/java/com/techeer/fmstudio/domain/banner/dao/BannerRepository.java
Labels: 기능 구현

#61 커스텀 배너 업데이트
  src/main/java/com/techeer/fmstudio/domain/banner/controller/CustomBannerController.java
  src/main/java/com/techeer/fmstudio/domain/banner/domain/BannerEntity.java
  src/main/java/com/techeer/fmstudio/domain/banner/dto/request/CustomBannerUpdateRequest.java
  src/main/java/com/techeer/fmstudio/domain/banner/service/CustomBannerService.java
Labels: 기능 구현

#63 S3 시크릿키 변수 이름 변경
  src/main/java/com/techeer/fmstudio/domain/banner/dao/BannerRepository.java
  src/main/java/com/techeer/fmstudio/domain/banner/service/CustomBannerService.java
  src/main/java/com/techeer/fmstudio/domain/s3/controller/S3Controller.java
  src/main/resources/application.yml
Labels: 리팩토링

#65 커스텀 & 오피셜 배너 불러오기 (페이지네이션), 일부 기능 미구현 상태
  src/main/java/com/techeer/fmstudio/domain/banner/controller/CustomBannerController.java
  src/main/java/com/techeer/fmstudio/domain/banner/controller/WholeBannerController.java
  src/main/java/com/techeer/fmstudio/domain/banner/dao/BannerRepository.java
  src/main/java/com/techeer/fmstudio/domain/banner/domain/BannerEntity.java
  src/main/java/com/techeer/fmstudio/domain/banner/dto/mapper/BannerMapper.java
  src/main/java/com/techeer/fmstudio/domain/banner/dto/response/BannerInfo.java
  src/main/java/com/techeer/fmstudio/domain/banner/dto/response/BannerPageInfo.java
  src/main/java/com/techeer/fmstudio/domain/banner/service/CustomBannerService.java
  src/main/java/com/techeer/fmstudio/domain/banner/service/WholeBannerService.java
Labels: 기능 구현

#66 커스텀 배너 불러오기 (페이지네이션), 일부 기능 미구현
  src/main/java/com/techeer/fmstudio/domain/banner/controller/CustomBannerController.java
  src/main/java/com/techeer/fmstudio/domain/banner/service/CustomBannerService.java
Labels: 기능 구현

#68 refactor: isFinished, isLiked, isIncluded 기능 더미 값 부여
  src/main/java/com/techeer/fmstudio/domain/banner/dto/mapper/BannerMapper.java
Labels: 리팩토링

#69 feat: 커스텀 배너 댓글 불러오기 (페이지네이션)
  src/main/java/com/techeer/fmstudio/domain/banner/controller/CustomCommentController.java
  src/main/java/com/techeer/fmstudio/domain/banner/dao/CommentRepository.java
  src/main/java/com/techeer/fmstudio/domain/banner/dto/mapper/CommentMapper.java
  src/main/java/com/techeer/fmstudio/domain/banner/dto/response/CommentPageInfo.java
  src/main/java/com/techeer/fmstudio/domain/banner/service/CustomCommentService.java
Labels: 기능 구현

#70 feat: 배너를 내 달력에서 삭제하기
  src/main/java/com/techeer/fmstudio/domain/banner/controller/CustomBannerController.java
  src/main/java/com/techeer/fmstudio/domain/banner/controller/CustomCommentController.java
  src/main/java/com/techeer/fmstudio/domain/banner/controller/WholeBannerController.java
  src/main/java/com/techeer/fmstudio/domain/banner/dao/MyBannerListRepository.java
  src/main/java/com/techeer/fmstudio/domain/banner/domain/MyBannerList.java
  src/main/java/com/techeer/fmstudio/domain/banner/dto/request/MyBannerDeleteRequest.java
  src/main/java/com/techeer/fmstudio/domain/banner/dto/response/DeleteResponse.java
  src/main/java/com/techeer/fmstudio/domain/banner/service/WholeBannerService.java
  src/main/resources/application.yml
Labels: 기능 구현

#72 refactor: 내 달력에 추가한 배너 관심사 분리
  src/main/java/com/techeer/fmstudio/domain/banner/controller/MyBannerListController.java
  src/main/java/com/techeer/fmstudio/domain/banner/controller/WholeBannerController.java
  src/main/java/com/techeer/fmstudio/domain/banner/service/MyBannerListService.java
  src/main/java/com/techeer/fmstudio/domain/banner/service/WholeBannerService.java
Labels: 리팩토링

#73 월별로 내 달력에 추가한 배너 일정 가져오기 기능
  src/main/java/com/techeer/fmstudio/domain/banner/controller/MyBannerListController.java
  src/main/java/com/techeer/fmstudio/domain/banner/dao/MyBannerListRepository.java
  src/main/java/com/techeer/fmstudio/domain/banner/domain/MyBannerList.java
  src/main/java/com/techeer/fmstudio/domain/banner/dto/mapper/MyBannerMapper.java
  src/main/java/com/techeer/fmstudio/domain/banner/dto/response/MyBannerCreateInfo.java
  src/main/java/com/techeer/fmstudio/domain/banner/dto/response/MyBannerInfo.java
  src/main/java/com/techeer/fmstudio/domain/banner/service/MyBannerListService.java
Labels: 기능 구현

#75 cross origin annotation 추가
  src/main/java/com/techeer/fmstudio/domain/banner/controller/CustomBannerController.java
  src/main/java/com/techeer/fmstudio/domain/banner/controller/CustomCommentController.java
  src/main/java/com/techeer/fmstudio/domain/banner/controller/MyBannerListController.java
  src/main/java/com/techeer/fmstudio/domain/banner/controller/WholeBannerController.java
  src/main/java/com/techeer/fmstudio/domain/s3/controller/S3Controller.java
  src/main/java/com/techeer/fmstudio/domain/task/controller/SharedMemberController.java
  src/main/java/com/techeer/fmstudio/domain/task/controller/TaskController.java
Labels: 오류 수정

#78 fix : 공유하지 않은 일정 삭제시 발생하는 에러 수정
  src/main/java/com/techeer/fmstudio/domain/task/service/SharedMemberService.java
Labels: 오류 수정
